import React from 'react';
import { Brain, Heart, Activity, Utensils, Moon, AlertCircle } from 'lucide-react';

interface AIRecommendationsProps {
  recommendations: string;
}

const AIRecommendations: React.FC<AIRecommendationsProps> = ({ recommendations }) => {
  const formatRecommendations = (text: string) => {
    // Split recommendations into sections
    const sections = text.split('\n\n');
    return sections.map((section, index) => {
      if (section.trim() === '') return null;
      
      // Determine icon based on content
      let icon = <Heart className="text-red-500" size={20} />;
      if (section.toLowerCase().includes('exercise') || section.toLowerCase().includes('physical')) {
        icon = <Activity className="text-blue-500" size={20} />;
      } else if (section.toLowerCase().includes('diet') || section.toLowerCase().includes('nutrition')) {
        icon = <Utensils className="text-green-500" size={20} />;
      } else if (section.toLowerCase().includes('sleep')) {
        icon = <Moon className="text-purple-500" size={20} />;
      }
      
      return (
        <div key={index} className="d-flex align-items-start mb-3">
          <div className="me-3 mt-1">{icon}</div>
          <div className="flex-grow-1">
            <p className="mb-0 text-muted lh-relaxed">{section.trim()}</p>
          </div>
        </div>
      );
    });
  };

  return (
    <section className="py-5 bg-gradient-to-r from-blue-50 to-indigo-50">
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-lg-10">
            <div className="card border-0 shadow-lg">
              <div className="card-body p-5">
                <div className="text-center mb-5">
                  <Brain className="text-primary mx-auto mb-3" size={48} />
                  <h2 className="display-6 fw-bold text-dark mb-3">
                    AI-Powered Health Recommendations
                  </h2>
                  <p className="lead text-muted">
                    Personalized recommendations based on your health assessment
                  </p>
                </div>

                <div className="row">
                  <div className="col-lg-12">
                    <div className="bg-light rounded-3 p-4 mb-4">
                      <div className="recommendations-content">
                        {formatRecommendations(recommendations)}
                      </div>
                    </div>
                  </div>
                </div>

                <div className="alert alert-info border-0 bg-blue-50 text-blue-800 d-flex align-items-start">
                  <AlertCircle className="me-3 mt-1 flex-shrink-0" size={20} />
                  <div>
                    <strong>AI Disclaimer:</strong> These recommendations are generated by artificial intelligence 
                    based on your health data. They are for informational purposes only and should complement, 
                    not replace, professional medical advice from qualified healthcare providers.
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default AIRecommendations;